// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmAssets extends Struct {
  public RmAssets __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int gold() { return bb.getInt(bb_pos + 0); }
  public int ruby() { return bb.getInt(bb_pos + 4); }

  public static int createRmAssets(FlatBufferBuilder builder, int gold, int ruby) {
    builder.prep(4, 8);
    builder.putInt(ruby);
    builder.putInt(gold);
    return builder.offset();
  }
}

