// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbResPlaylogList extends Table {
  public static RmbResPlaylogList getRootAsRmbResPlaylogList(ByteBuffer _bb) { return getRootAsRmbResPlaylogList(_bb, new RmbResPlaylogList()); }
  public static RmbResPlaylogList getRootAsRmbResPlaylogList(ByteBuffer _bb, RmbResPlaylogList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbResPlaylogList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public com.clue.fbs.RmPlaylog logs(int j) { return logs(new com.clue.fbs.RmPlaylog(), j); }
  public com.clue.fbs.RmPlaylog logs(com.clue.fbs.RmPlaylog obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int logsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createRmbResPlaylogList(FlatBufferBuilder builder,
      int logsOffset) {
    builder.startObject(1);
    RmbResPlaylogList.addLogs(builder, logsOffset);
    return RmbResPlaylogList.endRmbResPlaylogList(builder);
  }

  public static void startRmbResPlaylogList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addLogs(FlatBufferBuilder builder, int logsOffset) { builder.addOffset(0, logsOffset, 0); }
  public static int createLogsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLogsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRmbResPlaylogList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

