// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbReqUseHero extends Table {
  public static RmbReqUseHero getRootAsRmbReqUseHero(ByteBuffer _bb) { return getRootAsRmbReqUseHero(_bb, new RmbReqUseHero()); }
  public static RmbReqUseHero getRootAsRmbReqUseHero(ByteBuffer _bb, RmbReqUseHero obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbReqUseHero __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short name() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createRmbReqUseHero(FlatBufferBuilder builder,
      short name) {
    builder.startObject(1);
    RmbReqUseHero.addName(builder, name);
    return RmbReqUseHero.endRmbReqUseHero(builder);
  }

  public static void startRmbReqUseHero(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addName(FlatBufferBuilder builder, short name) { builder.addShort(0, name, 0); }
  public static int endRmbReqUseHero(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

