// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbResUseHero extends Table {
  public static RmbResUseHero getRootAsRmbResUseHero(ByteBuffer _bb) { return getRootAsRmbResUseHero(_bb, new RmbResUseHero()); }
  public static RmbResUseHero getRootAsRmbResUseHero(ByteBuffer _bb, RmbResUseHero obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbResUseHero __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short name() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public long lastPlay() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createRmbResUseHero(FlatBufferBuilder builder,
      short name,
      long lastPlay) {
    builder.startObject(2);
    RmbResUseHero.addLastPlay(builder, lastPlay);
    RmbResUseHero.addName(builder, name);
    return RmbResUseHero.endRmbResUseHero(builder);
  }

  public static void startRmbResUseHero(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, short name) { builder.addShort(0, name, 0); }
  public static void addLastPlay(FlatBufferBuilder builder, long lastPlay) { builder.addLong(1, lastPlay, 0); }
  public static int endRmbResUseHero(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

