// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbReqHeroes extends Table {
  public static RmbReqHeroes getRootAsRmbReqHeroes(ByteBuffer _bb) { return getRootAsRmbReqHeroes(_bb, new RmbReqHeroes()); }
  public static RmbReqHeroes getRootAsRmbReqHeroes(ByteBuffer _bb, RmbReqHeroes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbReqHeroes __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void startRmbReqHeroes(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endRmbReqHeroes(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

