// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbReqRouteMatch extends Table {
  public static RmbReqRouteMatch getRootAsRmbReqRouteMatch(ByteBuffer _bb) { return getRootAsRmbReqRouteMatch(_bb, new RmbReqRouteMatch()); }
  public static RmbReqRouteMatch getRootAsRmbReqRouteMatch(ByteBuffer _bb, RmbReqRouteMatch obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbReqRouteMatch __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String region() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer regionAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public byte league() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createRmbReqRouteMatch(FlatBufferBuilder builder,
      int regionOffset,
      byte league) {
    builder.startObject(2);
    RmbReqRouteMatch.addRegion(builder, regionOffset);
    RmbReqRouteMatch.addLeague(builder, league);
    return RmbReqRouteMatch.endRmbReqRouteMatch(builder);
  }

  public static void startRmbReqRouteMatch(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addRegion(FlatBufferBuilder builder, int regionOffset) { builder.addOffset(0, regionOffset, 0); }
  public static void addLeague(FlatBufferBuilder builder, byte league) { builder.addByte(1, league, 0); }
  public static int endRmbReqRouteMatch(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

