// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbResRouteMatch extends Table {
  public static RmbResRouteMatch getRootAsRmbResRouteMatch(ByteBuffer _bb) { return getRootAsRmbResRouteMatch(_bb, new RmbResRouteMatch()); }
  public static RmbResRouteMatch getRootAsRmbResRouteMatch(ByteBuffer _bb, RmbResRouteMatch obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbResRouteMatch __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String host() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createRmbResRouteMatch(FlatBufferBuilder builder,
      int hostOffset) {
    builder.startObject(1);
    RmbResRouteMatch.addHost(builder, hostOffset);
    return RmbResRouteMatch.endRmbResRouteMatch(builder);
  }

  public static void startRmbResRouteMatch(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(0, hostOffset, 0); }
  public static int endRmbResRouteMatch(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

