// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmHero extends Struct {
  public RmHero __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short name() { return bb.getShort(bb_pos + 0); }
  public int skin() { return bb.getInt(bb_pos + 4); }
  public long birth() { return bb.getLong(bb_pos + 8); }

  public static int createRmHero(FlatBufferBuilder builder, short name, int skin, long birth) {
    builder.prep(8, 16);
    builder.putLong(birth);
    builder.putInt(skin);
    builder.pad(2);
    builder.putShort(name);
    return builder.offset();
  }
}

