// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmAbnormal extends Struct {
  public RmmAbnormal __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte type() { return bb.get(bb_pos + 0); }
  public short from() { return bb.getShort(bb_pos + 2); }
  public short to() { return bb.getShort(bb_pos + 4); }
  public short at() { return bb.getShort(bb_pos + 6); }
  public short duration() { return bb.getShort(bb_pos + 8); }
  public short value() { return bb.getShort(bb_pos + 10); }

  public static int createRmmAbnormal(FlatBufferBuilder builder, byte type, short from, short to, short at, short duration, short value) {
    builder.prep(2, 12);
    builder.putShort(value);
    builder.putShort(duration);
    builder.putShort(at);
    builder.putShort(to);
    builder.putShort(from);
    builder.pad(1);
    builder.putByte(type);
    return builder.offset();
  }
}

