// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmBattleReward extends Struct {
  public RmmBattleReward __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short exp() { return bb.getShort(bb_pos + 0); }
  public byte league() { return bb.get(bb_pos + 2); }
  public short leaguePoint() { return bb.getShort(bb_pos + 4); }
  public short gold() { return bb.getShort(bb_pos + 6); }

  public static int createRmmBattleReward(FlatBufferBuilder builder, short exp, byte league, short leaguePoint, short gold) {
    builder.prep(2, 8);
    builder.putShort(gold);
    builder.putShort(leaguePoint);
    builder.pad(1);
    builder.putByte(league);
    builder.putShort(exp);
    return builder.offset();
  }
}

