// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiSync extends Table {
  public static RmmNotiSync getRootAsRmmNotiSync(ByteBuffer _bb) { return getRootAsRmmNotiSync(_bb, new RmmNotiSync()); }
  public static RmmNotiSync getRootAsRmmNotiSync(ByteBuffer _bb, RmmNotiSync obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiSync __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short sec() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public byte playerNo() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public RmmUnitOrder orders(int j) { return orders(new RmmUnitOrder(), j); }
  public RmmUnitOrder orders(RmmUnitOrder obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__vector(o) + j * 16, bb) : null; }
  public int ordersLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createRmmNotiSync(FlatBufferBuilder builder,
      short sec,
      byte playerNo,
      int ordersOffset) {
    builder.startObject(3);
    RmmNotiSync.addOrders(builder, ordersOffset);
    RmmNotiSync.addSec(builder, sec);
    RmmNotiSync.addPlayerNo(builder, playerNo);
    return RmmNotiSync.endRmmNotiSync(builder);
  }

  public static void startRmmNotiSync(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSec(FlatBufferBuilder builder, short sec) { builder.addShort(0, sec, 0); }
  public static void addPlayerNo(FlatBufferBuilder builder, byte playerNo) { builder.addByte(1, playerNo, 0); }
  public static void addOrders(FlatBufferBuilder builder, int ordersOffset) { builder.addOffset(2, ordersOffset, 0); }
  public static void startOrdersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 2); }
  public static int endRmmNotiSync(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

