// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiStart extends Table {
  public static RmmNotiStart getRootAsRmmNotiStart(ByteBuffer _bb) { return getRootAsRmmNotiStart(_bb, new RmmNotiStart()); }
  public static RmmNotiStart getRootAsRmmNotiStart(ByteBuffer _bb, RmmNotiStart obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiStart __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long startSec() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public short playSec() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createRmmNotiStart(FlatBufferBuilder builder,
      long startSec,
      short playSec) {
    builder.startObject(2);
    RmmNotiStart.addStartSec(builder, startSec);
    RmmNotiStart.addPlaySec(builder, playSec);
    return RmmNotiStart.endRmmNotiStart(builder);
  }

  public static void startRmmNotiStart(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addStartSec(FlatBufferBuilder builder, long startSec) { builder.addLong(0, startSec, 0); }
  public static void addPlaySec(FlatBufferBuilder builder, short playSec) { builder.addShort(1, playSec, 0); }
  public static int endRmmNotiStart(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

