// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiLvUp extends Table {
  public static RmmNotiLvUp getRootAsRmmNotiLvUp(ByteBuffer _bb) { return getRootAsRmmNotiLvUp(_bb, new RmmNotiLvUp()); }
  public static RmmNotiLvUp getRootAsRmmNotiLvUp(ByteBuffer _bb, RmmNotiLvUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiLvUp __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short key() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public byte level() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public short exp() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createRmmNotiLvUp(FlatBufferBuilder builder,
      short key,
      byte level,
      short exp) {
    builder.startObject(3);
    RmmNotiLvUp.addExp(builder, exp);
    RmmNotiLvUp.addKey(builder, key);
    RmmNotiLvUp.addLevel(builder, level);
    return RmmNotiLvUp.endRmmNotiLvUp(builder);
  }

  public static void startRmmNotiLvUp(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addKey(FlatBufferBuilder builder, short key) { builder.addShort(0, key, 0); }
  public static void addLevel(FlatBufferBuilder builder, byte level) { builder.addByte(1, level, 0); }
  public static void addExp(FlatBufferBuilder builder, short exp) { builder.addShort(2, exp, 0); }
  public static int endRmmNotiLvUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

