// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiRevival extends Table {
  public static RmmNotiRevival getRootAsRmmNotiRevival(ByteBuffer _bb) { return getRootAsRmmNotiRevival(_bb, new RmmNotiRevival()); }
  public static RmmNotiRevival getRootAsRmmNotiRevival(ByteBuffer _bb, RmmNotiRevival obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiRevival __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short sec() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public RmmUnit heroRevival() { return heroRevival(new RmmUnit()); }
  public RmmUnit heroRevival(RmmUnit obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createRmmNotiRevival(FlatBufferBuilder builder,
      short sec,
      int heroRevivalOffset) {
    builder.startObject(2);
    RmmNotiRevival.addHeroRevival(builder, heroRevivalOffset);
    RmmNotiRevival.addSec(builder, sec);
    return RmmNotiRevival.endRmmNotiRevival(builder);
  }

  public static void startRmmNotiRevival(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSec(FlatBufferBuilder builder, short sec) { builder.addShort(0, sec, 0); }
  public static void addHeroRevival(FlatBufferBuilder builder, int heroRevivalOffset) { builder.addOffset(1, heroRevivalOffset, 0); }
  public static int endRmmNotiRevival(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

