// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiPlaylog extends Table {
  public static RmmNotiPlaylog getRootAsRmmNotiPlaylog(ByteBuffer _bb) { return getRootAsRmmNotiPlaylog(_bb, new RmmNotiPlaylog()); }
  public static RmmNotiPlaylog getRootAsRmmNotiPlaylog(ByteBuffer _bb, RmmNotiPlaylog obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiPlaylog __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public com.clue.fbs.RmPlaylog logs() { return logs(new com.clue.fbs.RmPlaylog()); }
  public com.clue.fbs.RmPlaylog logs(com.clue.fbs.RmPlaylog obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createRmmNotiPlaylog(FlatBufferBuilder builder,
      int logsOffset) {
    builder.startObject(1);
    RmmNotiPlaylog.addLogs(builder, logsOffset);
    return RmmNotiPlaylog.endRmmNotiPlaylog(builder);
  }

  public static void startRmmNotiPlaylog(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addLogs(FlatBufferBuilder builder, int logsOffset) { builder.addOffset(0, logsOffset, 0); }
  public static int endRmmNotiPlaylog(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

