// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiLeave extends Table {
  public static RmmNotiLeave getRootAsRmmNotiLeave(ByteBuffer _bb) { return getRootAsRmmNotiLeave(_bb, new RmmNotiLeave()); }
  public static RmmNotiLeave getRootAsRmmNotiLeave(ByteBuffer _bb, RmmNotiLeave obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiLeave __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte playerNo() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createRmmNotiLeave(FlatBufferBuilder builder,
      byte playerNo) {
    builder.startObject(1);
    RmmNotiLeave.addPlayerNo(builder, playerNo);
    return RmmNotiLeave.endRmmNotiLeave(builder);
  }

  public static void startRmmNotiLeave(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPlayerNo(FlatBufferBuilder builder, byte playerNo) { builder.addByte(0, playerNo, 0); }
  public static int endRmmNotiLeave(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

