// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiEnd extends Table {
  public static RmmNotiEnd getRootAsRmmNotiEnd(ByteBuffer _bb) { return getRootAsRmmNotiEnd(_bb, new RmmNotiEnd()); }
  public static RmmNotiEnd getRootAsRmmNotiEnd(ByteBuffer _bb, RmmNotiEnd obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiEnd __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte winner() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public RmmPlayer player0() { return player0(new RmmPlayer()); }
  public RmmPlayer player0(RmmPlayer obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public RmmPlayer player1() { return player1(new RmmPlayer()); }
  public RmmPlayer player1(RmmPlayer obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public RmmBattleReward reward0() { return reward0(new RmmBattleReward()); }
  public RmmBattleReward reward0(RmmBattleReward obj) { int o = __offset(10); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public RmmBattleReward reward1() { return reward1(new RmmBattleReward()); }
  public RmmBattleReward reward1(RmmBattleReward obj) { int o = __offset(12); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void startRmmNotiEnd(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addWinner(FlatBufferBuilder builder, byte winner) { builder.addByte(0, winner, 0); }
  public static void addPlayer0(FlatBufferBuilder builder, int player0Offset) { builder.addOffset(1, player0Offset, 0); }
  public static void addPlayer1(FlatBufferBuilder builder, int player1Offset) { builder.addOffset(2, player1Offset, 0); }
  public static void addReward0(FlatBufferBuilder builder, int reward0Offset) { builder.addStruct(3, reward0Offset, 0); }
  public static void addReward1(FlatBufferBuilder builder, int reward1Offset) { builder.addStruct(4, reward1Offset, 0); }
  public static int endRmmNotiEnd(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

