// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmReqRoomList extends Table {
  public static RmmReqRoomList getRootAsRmmReqRoomList(ByteBuffer _bb) { return getRootAsRmmReqRoomList(_bb, new RmmReqRoomList()); }
  public static RmmReqRoomList getRootAsRmmReqRoomList(ByteBuffer _bb, RmmReqRoomList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmReqRoomList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short pageCount() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createRmmReqRoomList(FlatBufferBuilder builder,
      short pageCount) {
    builder.startObject(1);
    RmmReqRoomList.addPageCount(builder, pageCount);
    return RmmReqRoomList.endRmmReqRoomList(builder);
  }

  public static void startRmmReqRoomList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPageCount(FlatBufferBuilder builder, short pageCount) { builder.addShort(0, pageCount, 0); }
  public static int endRmmReqRoomList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

