// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmUnitOrder extends Struct {
  public RmmUnitOrder __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short from() { return bb.getShort(bb_pos + 0); }
  public short target() { return bb.getShort(bb_pos + 2); }
  public RmmVector2 position() { return position(new RmmVector2()); }
  public RmmVector2 position(RmmVector2 obj) { return obj.__init(bb_pos + 4, bb); }
  public RmmVector2 to() { return to(new RmmVector2()); }
  public RmmVector2 to(RmmVector2 obj) { return obj.__init(bb_pos + 8, bb); }
  public RmmVector2b direction() { return direction(new RmmVector2b()); }
  public RmmVector2b direction(RmmVector2b obj) { return obj.__init(bb_pos + 12, bb); }
  public byte state() { return bb.get(bb_pos + 14); }

  public static int createRmmUnitOrder(FlatBufferBuilder builder, short from, short target, short position_x, short position_z, short to_x, short to_z, byte direction_x, byte direction_z, byte state) {
    builder.prep(2, 16);
    builder.pad(1);
    builder.putByte(state);
    builder.prep(1, 2);
    builder.putByte(direction_z);
    builder.putByte(direction_x);
    builder.prep(2, 4);
    builder.putShort(to_z);
    builder.putShort(to_x);
    builder.prep(2, 4);
    builder.putShort(position_z);
    builder.putShort(position_x);
    builder.putShort(target);
    builder.putShort(from);
    return builder.offset();
  }
}

