// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmResultCode {
  private RmResultCode() { }
  public static final int Success = 0;
  public static final int DBError = 1;
  public static final int NotExist = 2;
  public static final int AlreadyExist = 3;
  public static final int NoAsset = 4;
  public static final int NotEnoughGold = 5;
  public static final int NotEnoughRuby = 6;
  public static final int OldVersion = 7;
  public static final int InternalError = 8;
  public static final int InsufficientLevel = 9;

  public static final String[] names = { "Success", "DBError", "NotExist", "AlreadyExist", "NoAsset", "NotEnoughGold", "NotEnoughRuby", "OldVersion", "InternalError", "InsufficientLevel", };

  public static String name(int e) { return names[e]; }
}

