// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmsAnimationInfo extends Struct {
  public RmsAnimationInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short name() { return bb.getShort(bb_pos + 0); }
  public float attackLength() { return bb.getFloat(bb_pos + 4); }
  public float skill1Length() { return bb.getFloat(bb_pos + 8); }
  public float skill2Length() { return bb.getFloat(bb_pos + 12); }
  public float skill3Length() { return bb.getFloat(bb_pos + 16); }
  public byte attackCount() { return bb.get(bb_pos + 20); }
  public byte skill1Count() { return bb.get(bb_pos + 21); }
  public byte skill2Count() { return bb.get(bb_pos + 22); }
  public byte skill3Count() { return bb.get(bb_pos + 23); }

  public static int createRmsAnimationInfo(FlatBufferBuilder builder, short name, float attackLength, float skill1Length, float skill2Length, float skill3Length, byte attackCount, byte skill1Count, byte skill2Count, byte skill3Count) {
    builder.prep(4, 24);
    builder.putByte(skill3Count);
    builder.putByte(skill2Count);
    builder.putByte(skill1Count);
    builder.putByte(attackCount);
    builder.putFloat(skill3Length);
    builder.putFloat(skill2Length);
    builder.putFloat(skill1Length);
    builder.putFloat(attackLength);
    builder.pad(2);
    builder.putShort(name);
    return builder.offset();
  }
}

