// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmsHeroRevival extends Struct {
  public RmsHeroRevival __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int level() { return bb.getInt(bb_pos + 0); }
  public int sec() { return bb.getInt(bb_pos + 4); }

  public static int createRmsHeroRevival(FlatBufferBuilder builder, int level, int sec) {
    builder.prep(4, 8);
    builder.putInt(sec);
    builder.putInt(level);
    return builder.offset();
  }
}

