// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmsLeagueBalance extends Struct {
  public RmsLeagueBalance __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int league() { return bb.getInt(bb_pos + 0); }
  public int point() { return bb.getInt(bb_pos + 4); }
  public short gold() { return bb.getShort(bb_pos + 8); }

  public static int createRmsLeagueBalance(FlatBufferBuilder builder, int league, int point, short gold) {
    builder.prep(4, 12);
    builder.pad(2);
    builder.putShort(gold);
    builder.putInt(point);
    builder.putInt(league);
    return builder.offset();
  }
}

