// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmsSkillBalance extends Struct {
  public RmsSkillBalance __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short skillType() { return bb.getShort(bb_pos + 0); }
  public int level() { return bb.getInt(bb_pos + 4); }
  public float attackScalar() { return bb.getFloat(bb_pos + 8); }
  public float lifeTime() { return bb.getFloat(bb_pos + 12); }
  public float coolTime() { return bb.getFloat(bb_pos + 16); }
  public int abnormal() { return bb.getInt(bb_pos + 20); }

  public static int createRmsSkillBalance(FlatBufferBuilder builder, short skillType, int level, float attackScalar, float lifeTime, float coolTime, int abnormal) {
    builder.prep(4, 24);
    builder.putInt(abnormal);
    builder.putFloat(coolTime);
    builder.putFloat(lifeTime);
    builder.putFloat(attackScalar);
    builder.putInt(level);
    builder.pad(2);
    builder.putShort(skillType);
    return builder.offset();
  }
}

