// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmsUnitStatic extends Struct {
  public RmsUnitStatic __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int order() { return bb.getInt(bb_pos + 0); }
  public byte type() { return bb.get(bb_pos + 4); }
  public short name() { return bb.getShort(bb_pos + 6); }
  public int minUserLevel() { return bb.getInt(bb_pos + 8); }
  public int price() { return bb.getInt(bb_pos + 12); }
  public short skill1() { return bb.getShort(bb_pos + 16); }
  public short skill2() { return bb.getShort(bb_pos + 18); }
  public short skill3() { return bb.getShort(bb_pos + 20); }
  public float moveSpeed() { return bb.getFloat(bb_pos + 24); }
  public float attackCooltime() { return bb.getFloat(bb_pos + 28); }
  public float attackRange() { return bb.getFloat(bb_pos + 32); }
  public float hpRegen() { return bb.getFloat(bb_pos + 36); }

  public static int createRmsUnitStatic(FlatBufferBuilder builder, int order, byte type, short name, int minUserLevel, int price, short skill1, short skill2, short skill3, float moveSpeed, float attackCooltime, float attackRange, float hpRegen) {
    builder.prep(4, 40);
    builder.putFloat(hpRegen);
    builder.putFloat(attackRange);
    builder.putFloat(attackCooltime);
    builder.putFloat(moveSpeed);
    builder.pad(2);
    builder.putShort(skill3);
    builder.putShort(skill2);
    builder.putShort(skill1);
    builder.putInt(price);
    builder.putInt(minUserLevel);
    builder.putShort(name);
    builder.pad(1);
    builder.putByte(type);
    builder.putInt(order);
    return builder.offset();
  }
}

