// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmUnitType {
  private RmUnitType() { }
  public static final byte Hero = 0;
  public static final byte Pet = 1;

  public static final String[] names = { "Hero", "Pet", };

  public static String name(int e) { return names[e]; }
}

