<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmAbnormalType
{
    const None = 0;
    const Slow = 1;
    const Iced = 2;
    const Restrained = 3;
    const Frozen = 4;
    const Bleeding = 5;
    const Berserk = 6;
    const Charm = 7;
    const Fear = 8;

    private static $names = array(
        "None",
        "Slow",
        "Iced",
        "Restrained",
        "Frozen",
        "Bleeding",
        "Berserk",
        "Charm",
        "Fear",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
