<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmbMessageType
{
    const Error = 0;
    const Ping = 1;
    const Pong = 2;
    const ReqLogin = 3;
    const ResLogin = 4;
    const ReqHeroes = 5;
    const ResHeroes = 6;
    const ReqBuyHero = 7;
    const ResBuyHero = 8;
    const ReqRouteMatch = 9;
    const ResRouteMatch = 10;
    const ReqPlaylogList = 11;
    const ResPlaylogList = 12;
    const ReqSetName = 13;
    const ResSetName = 14;
    const ReqUseHero = 15;
    const ResUseHero = 16;

    private static $names = array(
        "Error",
        "Ping",
        "Pong",
        "ReqLogin",
        "ResLogin",
        "ReqHeroes",
        "ResHeroes",
        "ReqBuyHero",
        "ResBuyHero",
        "ReqRouteMatch",
        "ResRouteMatch",
        "ReqPlaylogList",
        "ResPlaylogList",
        "ReqSetName",
        "ResSetName",
        "ReqUseHero",
        "ResUseHero",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
