<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmbReqLogin extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RmbReqLogin
     */
    public static function getRootAsRmbReqLogin(ByteBuffer $bb)
    {
        $obj = new RmbReqLogin();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmbReqLogin
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getUid()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getCountry()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getVersion()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return int
     */
    public function getMetaVersion()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRmbReqLogin(FlatBufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RmbReqLogin
     */
    public static function createRmbReqLogin(FlatBufferBuilder $builder, $uid, $country, $version, $metaVersion)
    {
        $builder->startObject(4);
        self::addUid($builder, $uid);
        self::addCountry($builder, $country);
        self::addVersion($builder, $version);
        self::addMetaVersion($builder, $metaVersion);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addUid(FlatBufferBuilder $builder, $uid)
    {
        $builder->addOffsetX(0, $uid, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addCountry(FlatBufferBuilder $builder, $country)
    {
        $builder->addOffsetX(1, $country, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addVersion(FlatBufferBuilder $builder, $version)
    {
        $builder->addOffsetX(2, $version, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addMetaVersion(FlatBufferBuilder $builder, $metaVersion)
    {
        $builder->addIntX(3, $metaVersion, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRmbReqLogin(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
