<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmbReqRouteMatch extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RmbReqRouteMatch
     */
    public static function getRootAsRmbReqRouteMatch(ByteBuffer $bb)
    {
        $obj = new RmbReqRouteMatch();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmbReqRouteMatch
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getRegion()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return sbyte
     */
    public function getLeague()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRmbReqRouteMatch(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RmbReqRouteMatch
     */
    public static function createRmbReqRouteMatch(FlatBufferBuilder $builder, $region, $league)
    {
        $builder->startObject(2);
        self::addRegion($builder, $region);
        self::addLeague($builder, $league);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addRegion(FlatBufferBuilder $builder, $region)
    {
        $builder->addOffsetX(0, $region, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addLeague(FlatBufferBuilder $builder, $league)
    {
        $builder->addSbyteX(1, $league, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRmbReqRouteMatch(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
