<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmbResRouteMatch extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RmbResRouteMatch
     */
    public static function getRootAsRmbResRouteMatch(ByteBuffer $bb)
    {
        $obj = new RmbResRouteMatch();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmbResRouteMatch
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getHost()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRmbResRouteMatch(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RmbResRouteMatch
     */
    public static function createRmbResRouteMatch(FlatBufferBuilder $builder, $host)
    {
        $builder->startObject(1);
        self::addHost($builder, $host);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addHost(FlatBufferBuilder $builder, $host)
    {
        $builder->addOffsetX(0, $host, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRmbResRouteMatch(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
