<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmmBattleReward extends Struct
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmmBattleReward
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return short
     */
    public function GetExp()
    {
        return $this->bb->getShort($this->bb_pos + 0);
    }

    /**
     * @return sbyte
     */
    public function GetLeague()
    {
        return $this->bb->getSbyte($this->bb_pos + 2);
    }

    /**
     * @return short
     */
    public function GetLeaguePoint()
    {
        return $this->bb->getShort($this->bb_pos + 4);
    }

    /**
     * @return short
     */
    public function GetGold()
    {
        return $this->bb->getShort($this->bb_pos + 6);
    }


    /**
     * @return int offset
     */
    public static function createRmmBattleReward(FlatBufferBuilder $builder, $exp, $league, $leaguePoint, $gold)
    {
        $builder->prep(2, 8);
        $builder->putShort($gold);
        $builder->putShort($leaguePoint);
        $builder->pad(1);
        $builder->putSbyte($league);
        $builder->putShort($exp);
        return $builder->offset();
    }
}
