<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmmMessageType
{
    const ReqJoin = 0;
    const ResJoin = 1;
    const NotiJoin = 2;
    const ReqReJoin = 3;
    const ResReJoin = 4;
    const NotiReJoin = 5;
    const NotiStart = 6;
    const ReqSync = 7;
    const NotiSync = 8;
    const NotiDeploy = 9;
    const NotiDamage = 10;
    const NotiAbnormal = 11;
    const NotiRevival = 12;
    const NotiLvUp = 13;
    const NotiLeave = 14;
    const ResSyncError = 15;
    const NotiEnd = 16;
    const NotiPlaylog = 17;
    const ReqRoomList = 18;
    const ResRoomList = 19;

    private static $names = array(
        "ReqJoin",
        "ResJoin",
        "NotiJoin",
        "ReqReJoin",
        "ResReJoin",
        "NotiReJoin",
        "NotiStart",
        "ReqSync",
        "NotiSync",
        "NotiDeploy",
        "NotiDamage",
        "NotiAbnormal",
        "NotiRevival",
        "NotiLvUp",
        "NotiLeave",
        "ResSyncError",
        "NotiEnd",
        "NotiPlaylog",
        "ReqRoomList",
        "ResRoomList",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
