<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmmNotiDamage extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RmmNotiDamage
     */
    public static function getRootAsRmmNotiDamage(ByteBuffer $bb)
    {
        $obj = new RmmNotiDamage();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmmNotiDamage
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return short
     */
    public function getSec()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : 0;
    }

    /**
     * @returnVectorOffset
     */
    public function getDamages($j)
    {
        $o = $this->__offset(6);
        $obj = new RmmUnitDamage();
        return $o != 0 ? $obj->init($this->__vector($o) + $j *12, $this->bb) : null;
    }

    /**
     * @return int
     */
    public function getDamagesLength()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRmmNotiDamage(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RmmNotiDamage
     */
    public static function createRmmNotiDamage(FlatBufferBuilder $builder, $sec, $damages)
    {
        $builder->startObject(2);
        self::addSec($builder, $sec);
        self::addDamages($builder, $damages);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addSec(FlatBufferBuilder $builder, $sec)
    {
        $builder->addShortX(0, $sec, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addDamages(FlatBufferBuilder $builder, $damages)
    {
        $builder->addOffsetX(1, $damages, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createDamagesVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(12, count($data), 2);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->addOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startDamagesVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(12, $numElems, 2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRmmNotiDamage(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
