<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmmNotiRevival extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RmmNotiRevival
     */
    public static function getRootAsRmmNotiRevival(ByteBuffer $bb)
    {
        $obj = new RmmNotiRevival();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmmNotiRevival
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return short
     */
    public function getSec()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : 0;
    }

    public function getHeroRevival()
    {
        $obj = new RmmUnit();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRmmNotiRevival(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RmmNotiRevival
     */
    public static function createRmmNotiRevival(FlatBufferBuilder $builder, $sec, $heroRevival)
    {
        $builder->startObject(2);
        self::addSec($builder, $sec);
        self::addHeroRevival($builder, $heroRevival);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addSec(FlatBufferBuilder $builder, $sec)
    {
        $builder->addShortX(0, $sec, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addHeroRevival(FlatBufferBuilder $builder, $heroRevival)
    {
        $builder->addOffsetX(1, $heroRevival, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRmmNotiRevival(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
