<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmmRoomType
{
    const None = 0;
    const Room1vs1 = 1;
    const Room2vs2 = 2;
    const Room3vs3 = 3;

    private static $names = array(
        "None",
        "Room1vs1",
        "Room2vs2",
        "Room3vs3",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
