<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmmReqRoomList extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RmmReqRoomList
     */
    public static function getRootAsRmmReqRoomList(ByteBuffer $bb)
    {
        $obj = new RmmReqRoomList();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmmReqRoomList
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return short
     */
    public function getPageCount()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRmmReqRoomList(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RmmReqRoomList
     */
    public static function createRmmReqRoomList(FlatBufferBuilder $builder, $pageCount)
    {
        $builder->startObject(1);
        self::addPageCount($builder, $pageCount);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addPageCount(FlatBufferBuilder $builder, $pageCount)
    {
        $builder->addShortX(0, $pageCount, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRmmReqRoomList(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
