<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmmRoomState
{
    const Open = 0;
    const Play = 1;
    const Closed = 2;

    private static $names = array(
        "Open",
        "Play",
        "Closed",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
