<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmmVector2b extends Struct
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmmVector2b
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return sbyte
     */
    public function GetX()
    {
        return $this->bb->getSbyte($this->bb_pos + 0);
    }

    /**
     * @return sbyte
     */
    public function GetZ()
    {
        return $this->bb->getSbyte($this->bb_pos + 1);
    }


    /**
     * @return int offset
     */
    public static function createRmmVector2b(FlatBufferBuilder $builder, $x, $z)
    {
        $builder->prep(1, 2);
        $builder->putSbyte($z);
        $builder->putSbyte($x);
        return $builder->offset();
    }
}
