<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmmVector2 extends Struct
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmmVector2
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return short
     */
    public function GetX()
    {
        return $this->bb->getShort($this->bb_pos + 0);
    }

    /**
     * @return short
     */
    public function GetZ()
    {
        return $this->bb->getShort($this->bb_pos + 2);
    }


    /**
     * @return int offset
     */
    public static function createRmmVector2(FlatBufferBuilder $builder, $x, $z)
    {
        $builder->prep(2, 4);
        $builder->putShort($z);
        $builder->putShort($x);
        return $builder->offset();
    }
}
