<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmResultCode
{
    const Success = 0;
    const DBError = 1;
    const NotExist = 2;
    const AlreadyExist = 3;
    const NoAsset = 4;
    const NotEnoughGold = 5;
    const NotEnoughRuby = 6;
    const OldVersion = 7;

    private static $names = array(
        "Success",
        "DBError",
        "NotExist",
        "AlreadyExist",
        "NoAsset",
        "NotEnoughGold",
        "NotEnoughRuby",
        "OldVersion",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
