<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmsAbnormalBalance extends Struct
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmsAbnormalBalance
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function GetKey()
    {
        return $this->bb->getInt($this->bb_pos + 0);
    }

    /**
     * @return sbyte
     */
    public function GetType()
    {
        return $this->bb->getSbyte($this->bb_pos + 4);
    }

    /**
     * @return float
     */
    public function GetDuration()
    {
        return $this->bb->getFloat($this->bb_pos + 8);
    }

    /**
     * @return float
     */
    public function GetValue()
    {
        return $this->bb->getFloat($this->bb_pos + 12);
    }


    /**
     * @return int offset
     */
    public static function createRmsAbnormalBalance(FlatBufferBuilder $builder, $key, $type, $duration, $value)
    {
        $builder->prep(4, 16);
        $builder->putFloat($value);
        $builder->putFloat($duration);
        $builder->pad(3);
        $builder->putSbyte($type);
        $builder->putInt($key);
        return $builder->offset();
    }
}
