<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmSkillType
{
    const None = 0;
    const IceSmash = 1;
    const IceWhirlWind = 2;
    const MultiArrow = 3;
    const HolyArrow = 4;
    const Lightning = 5;
    const MultiBolt = 6;

    private static $names = array(
        "None",
        "IceSmash",
        "IceWhirlWind",
        "MultiArrow",
        "HolyArrow",
        "Lightning",
        "MultiBolt",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
