<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmsLeagueBalance extends Struct
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmsLeagueBalance
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function GetLeague()
    {
        return $this->bb->getInt($this->bb_pos + 0);
    }

    /**
     * @return int
     */
    public function GetPoint()
    {
        return $this->bb->getInt($this->bb_pos + 4);
    }

    /**
     * @return short
     */
    public function GetGold()
    {
        return $this->bb->getShort($this->bb_pos + 8);
    }


    /**
     * @return int offset
     */
    public static function createRmsLeagueBalance(FlatBufferBuilder $builder, $league, $point, $gold)
    {
        $builder->prep(4, 12);
        $builder->pad(2);
        $builder->putShort($gold);
        $builder->putInt($point);
        $builder->putInt($league);
        return $builder->offset();
    }
}
