<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmStatType
{
    const None = 0;
    const Health = 1;
    const PhysicalAttack = 2;
    const MagicalAttack = 3;
    const PhysicalDefence = 4;
    const MagicalDefence = 5;
    const HealthBoost = 31;
    const PhysicalAttackBoost = 32;
    const MagicalAttackBoost = 33;
    const PhysicalDefenceBoost = 34;
    const MagicalDefenceBoost = 35;
    const MoveSpeedBoost = 61;
    const AttackSpeedBoost = 62;
    const DamageReduce = 63;
    const CooltimeReduce = 64;

    private static $names = array(
        "None",
        "Health",
        "PhysicalAttack",
        "MagicalAttack",
        "PhysicalDefence",
        "MagicalDefence",
        "HealthBoost",
        "PhysicalAttackBoost",
        "MagicalAttackBoost",
        "PhysicalDefenceBoost",
        "MagicalDefenceBoost",
        "MoveSpeedBoost",
        "AttackSpeedBoost",
        "DamageReduce",
        "CooltimeReduce",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
