<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RmsUnitStatic extends Struct
{
    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RmsUnitStatic
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function GetOrder()
    {
        return $this->bb->getInt($this->bb_pos + 0);
    }

    /**
     * @return sbyte
     */
    public function GetType()
    {
        return $this->bb->getSbyte($this->bb_pos + 4);
    }

    /**
     * @return short
     */
    public function GetName()
    {
        return $this->bb->getShort($this->bb_pos + 6);
    }

    /**
     * @return int
     */
    public function GetMinUserLevel()
    {
        return $this->bb->getInt($this->bb_pos + 8);
    }

    /**
     * @return int
     */
    public function GetPrice()
    {
        return $this->bb->getInt($this->bb_pos + 12);
    }

    /**
     * @return short
     */
    public function GetSkill1()
    {
        return $this->bb->getShort($this->bb_pos + 16);
    }

    /**
     * @return short
     */
    public function GetSkill2()
    {
        return $this->bb->getShort($this->bb_pos + 18);
    }

    /**
     * @return short
     */
    public function GetSkill3()
    {
        return $this->bb->getShort($this->bb_pos + 20);
    }

    /**
     * @return float
     */
    public function GetMoveSpeed()
    {
        return $this->bb->getFloat($this->bb_pos + 24);
    }

    /**
     * @return float
     */
    public function GetAttackCooltime()
    {
        return $this->bb->getFloat($this->bb_pos + 28);
    }

    /**
     * @return float
     */
    public function GetAttackRange()
    {
        return $this->bb->getFloat($this->bb_pos + 32);
    }

    /**
     * @return float
     */
    public function GetHpRegen()
    {
        return $this->bb->getFloat($this->bb_pos + 36);
    }


    /**
     * @return int offset
     */
    public static function createRmsUnitStatic(FlatBufferBuilder $builder, $order, $type, $name, $minUserLevel, $price, $skill1, $skill2, $skill3, $moveSpeed, $attackCooltime, $attackRange, $hpRegen)
    {
        $builder->prep(4, 40);
        $builder->putFloat($hpRegen);
        $builder->putFloat($attackRange);
        $builder->putFloat($attackCooltime);
        $builder->putFloat($moveSpeed);
        $builder->pad(2);
        $builder->putShort($skill3);
        $builder->putShort($skill2);
        $builder->putShort($skill1);
        $builder->putInt($price);
        $builder->putInt($minUserLevel);
        $builder->putShort($name);
        $builder->pad(1);
        $builder->putSbyte($type);
        $builder->putInt($order);
        return $builder->offset();
    }
}
