<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmUnitName
{
    const None = 0;
    const IceKnight = 1;
    const HolyArcher = 2;
    const Wizard = 3;
    const Valkyrie = 4;
    const Cannon = 5;
    const DeathCaller = 6;
    const Dullahan = 7;
    const Eros = 8;
    const Gangster = 9;
    const General = 10;
    const Gunner = 11;
    const IceQueen = 12;
    const Immortal = 13;
    const LineMan = 14;
    const Monk = 15;
    const Paoh = 16;
    const Pharaoh = 17;
    const Priest = 18;
    const SandWitch = 19;
    const Succubus = 20;
    const Thief = 21;
    const Anna = 22;
    const SkeletonBasic = 101;
    const SkeletonBow = 102;
    const SkeletonKing = 103;
    const SkeletonMage = 104;
    const Tower = 201;

    private static $names = array(
        "None",
        "IceKnight",
        "HolyArcher",
        "Wizard",
        "Valkyrie",
        "Cannon",
        "DeathCaller",
        "Dullahan",
        "Eros",
        "Gangster",
        "General",
        "Gunner",
        "IceQueen",
        "Immortal",
        "LineMan",
        "Monk",
        "Paoh",
        "Pharaoh",
        "Priest",
        "SandWitch",
        "Succubus",
        "Thief",
        "Anna",
        "SkeletonBasic",
        "SkeletonBow",
        "SkeletonKing",
        "SkeletonMage",
        "Tower",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
