<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace com\clue\fbs;

class RmUnitType
{
    const Hero = 0;
    const Pet = 1;

    private static $names = array(
        "Hero",
        "Pet",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
