// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmAbnormalType {
  private RmAbnormalType() { }
  public static final byte None = 0;
  public static final byte Slow = 1;
  public static final byte Iced = 2;
  public static final byte Restrained = 3;
  public static final byte Frozen = 4;
  public static final byte Bleeding = 5;
  public static final byte Berserk = 6;
  public static final byte Charm = 7;
  public static final byte Fear = 8;

  public static final String[] names = { "None", "Slow", "Iced", "Restrained", "Frozen", "Bleeding", "Berserk", "Charm", "Fear", };

  public static String name(int e) { return names[e]; }
}

