// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmAccount extends Table {
  public static RmAccount getRootAsRmAccount(ByteBuffer _bb) { return getRootAsRmAccount(_bb, new RmAccount()); }
  public static RmAccount getRootAsRmAccount(ByteBuffer _bb, RmAccount obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmAccount __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String uid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int token() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String profileUrl() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileUrlAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public long birth() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String facebook() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer facebookAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String google() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer googleAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public String gameCenter() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer gameCenterAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public int level() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int exp() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte league() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int leaguePoint() { int o = __offset(26); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String country() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer countryAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public long lastPlayTime() { int o = __offset(30); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createRmAccount(FlatBufferBuilder builder,
      int uidOffset,
      int token,
      int nameOffset,
      int profileUrlOffset,
      long birth,
      int facebookOffset,
      int googleOffset,
      int gameCenterOffset,
      int level,
      int exp,
      byte league,
      int leaguePoint,
      int countryOffset,
      long lastPlayTime) {
    builder.startObject(14);
    RmAccount.addLastPlayTime(builder, lastPlayTime);
    RmAccount.addBirth(builder, birth);
    RmAccount.addCountry(builder, countryOffset);
    RmAccount.addLeaguePoint(builder, leaguePoint);
    RmAccount.addExp(builder, exp);
    RmAccount.addLevel(builder, level);
    RmAccount.addGameCenter(builder, gameCenterOffset);
    RmAccount.addGoogle(builder, googleOffset);
    RmAccount.addFacebook(builder, facebookOffset);
    RmAccount.addProfileUrl(builder, profileUrlOffset);
    RmAccount.addName(builder, nameOffset);
    RmAccount.addToken(builder, token);
    RmAccount.addUid(builder, uidOffset);
    RmAccount.addLeague(builder, league);
    return RmAccount.endRmAccount(builder);
  }

  public static void startRmAccount(FlatBufferBuilder builder) { builder.startObject(14); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(0, uidOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int token) { builder.addInt(1, token, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(2, nameOffset, 0); }
  public static void addProfileUrl(FlatBufferBuilder builder, int profileUrlOffset) { builder.addOffset(3, profileUrlOffset, 0); }
  public static void addBirth(FlatBufferBuilder builder, long birth) { builder.addLong(4, birth, 0); }
  public static void addFacebook(FlatBufferBuilder builder, int facebookOffset) { builder.addOffset(5, facebookOffset, 0); }
  public static void addGoogle(FlatBufferBuilder builder, int googleOffset) { builder.addOffset(6, googleOffset, 0); }
  public static void addGameCenter(FlatBufferBuilder builder, int gameCenterOffset) { builder.addOffset(7, gameCenterOffset, 0); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addInt(8, level, 0); }
  public static void addExp(FlatBufferBuilder builder, int exp) { builder.addInt(9, exp, 0); }
  public static void addLeague(FlatBufferBuilder builder, byte league) { builder.addByte(10, league, 0); }
  public static void addLeaguePoint(FlatBufferBuilder builder, int leaguePoint) { builder.addInt(11, leaguePoint, 0); }
  public static void addCountry(FlatBufferBuilder builder, int countryOffset) { builder.addOffset(12, countryOffset, 0); }
  public static void addLastPlayTime(FlatBufferBuilder builder, long lastPlayTime) { builder.addLong(13, lastPlayTime, 0); }
  public static int endRmAccount(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

