// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmbMessageType {
  private RmbMessageType() { }
  public static final byte Error = 0;
  public static final byte Ping = 1;
  public static final byte Pong = 2;
  public static final byte ReqLogin = 3;
  public static final byte ResLogin = 4;
  public static final byte ReqHeroes = 5;
  public static final byte ResHeroes = 6;
  public static final byte ReqBuyHero = 7;
  public static final byte ResBuyHero = 8;
  public static final byte ReqRouteMatch = 9;
  public static final byte ResRouteMatch = 10;
  public static final byte ReqPlaylogList = 11;
  public static final byte ResPlaylogList = 12;
  public static final byte ReqSetName = 13;
  public static final byte ResSetName = 14;

  public static final String[] names = { "Error", "Ping", "Pong", "ReqLogin", "ResLogin", "ReqHeroes", "ResHeroes", "ReqBuyHero", "ResBuyHero", "ReqRouteMatch", "ResRouteMatch", "ReqPlaylogList", "ResPlaylogList", "ReqSetName", "ResSetName", };

  public static String name(int e) { return names[e]; }
}

