// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbResHeroes extends Table {
  public static RmbResHeroes getRootAsRmbResHeroes(ByteBuffer _bb) { return getRootAsRmbResHeroes(_bb, new RmbResHeroes()); }
  public static RmbResHeroes getRootAsRmbResHeroes(ByteBuffer _bb, RmbResHeroes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbResHeroes __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public com.clue.fbs.RmHero heroes(int j) { return heroes(new com.clue.fbs.RmHero(), j); }
  public com.clue.fbs.RmHero heroes(com.clue.fbs.RmHero obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__vector(o) + j * 16, bb) : null; }
  public int heroesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createRmbResHeroes(FlatBufferBuilder builder,
      int heroesOffset) {
    builder.startObject(1);
    RmbResHeroes.addHeroes(builder, heroesOffset);
    return RmbResHeroes.endRmbResHeroes(builder);
  }

  public static void startRmbResHeroes(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addHeroes(FlatBufferBuilder builder, int heroesOffset) { builder.addOffset(0, heroesOffset, 0); }
  public static void startHeroesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static int endRmbResHeroes(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

