// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbResLogin extends Table {
  public static RmbResLogin getRootAsRmbResLogin(ByteBuffer _bb) { return getRootAsRmbResLogin(_bb, new RmbResLogin()); }
  public static RmbResLogin getRootAsRmbResLogin(ByteBuffer _bb, RmbResLogin obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbResLogin __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public com.clue.fbs.RmAccount account() { return account(new com.clue.fbs.RmAccount()); }
  public com.clue.fbs.RmAccount account(com.clue.fbs.RmAccount obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public com.clue.fbs.RmAssets assets() { return assets(new com.clue.fbs.RmAssets()); }
  public com.clue.fbs.RmAssets assets(com.clue.fbs.RmAssets obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public int metaVersion() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte metaSet(int j) { int o = __offset(10); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int metaSetLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer metaSetAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static void startRmbResLogin(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addAccount(FlatBufferBuilder builder, int accountOffset) { builder.addOffset(0, accountOffset, 0); }
  public static void addAssets(FlatBufferBuilder builder, int assetsOffset) { builder.addStruct(1, assetsOffset, 0); }
  public static void addMetaVersion(FlatBufferBuilder builder, int metaVersion) { builder.addInt(2, metaVersion, 0); }
  public static void addMetaSet(FlatBufferBuilder builder, int metaSetOffset) { builder.addOffset(3, metaSetOffset, 0); }
  public static int createMetaSetVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startMetaSetVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endRmbResLogin(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

