// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmbReqSetName extends Table {
  public static RmbReqSetName getRootAsRmbReqSetName(ByteBuffer _bb) { return getRootAsRmbReqSetName(_bb, new RmbReqSetName()); }
  public static RmbReqSetName getRootAsRmbReqSetName(ByteBuffer _bb, RmbReqSetName obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmbReqSetName __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createRmbReqSetName(FlatBufferBuilder builder,
      int nameOffset) {
    builder.startObject(1);
    RmbReqSetName.addName(builder, nameOffset);
    return RmbReqSetName.endRmbReqSetName(builder);
  }

  public static void startRmbReqSetName(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static int endRmbReqSetName(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

