// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmNotiDeploy extends Table {
  public static RmmNotiDeploy getRootAsRmmNotiDeploy(ByteBuffer _bb) { return getRootAsRmmNotiDeploy(_bb, new RmmNotiDeploy()); }
  public static RmmNotiDeploy getRootAsRmmNotiDeploy(ByteBuffer _bb, RmmNotiDeploy obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmNotiDeploy __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short sec() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public RmmUnit deploy(int j) { return deploy(new RmmUnit(), j); }
  public RmmUnit deploy(RmmUnit obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int deployLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createRmmNotiDeploy(FlatBufferBuilder builder,
      short sec,
      int deployOffset) {
    builder.startObject(2);
    RmmNotiDeploy.addDeploy(builder, deployOffset);
    RmmNotiDeploy.addSec(builder, sec);
    return RmmNotiDeploy.endRmmNotiDeploy(builder);
  }

  public static void startRmmNotiDeploy(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSec(FlatBufferBuilder builder, short sec) { builder.addShort(0, sec, 0); }
  public static void addDeploy(FlatBufferBuilder builder, int deployOffset) { builder.addOffset(1, deployOffset, 0); }
  public static int createDeployVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDeployVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRmmNotiDeploy(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

