// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmmRoomType {
  private RmmRoomType() { }
  public static final byte None = 0;
  public static final byte Room1vs1 = 1;
  public static final byte Room2vs2 = 2;
  public static final byte Room3vs3 = 3;

  public static final String[] names = { "None", "Room1vs1", "Room2vs2", "Room3vs3", };

  public static String name(int e) { return names[e]; }
}

