// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmmResSyncError extends Table {
  public static RmmResSyncError getRootAsRmmResSyncError(ByteBuffer _bb) { return getRootAsRmmResSyncError(_bb, new RmmResSyncError()); }
  public static RmmResSyncError getRootAsRmmResSyncError(ByteBuffer _bb, RmmResSyncError obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmmResSyncError __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte playerNo() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte reason() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createRmmResSyncError(FlatBufferBuilder builder,
      byte playerNo,
      byte reason) {
    builder.startObject(2);
    RmmResSyncError.addReason(builder, reason);
    RmmResSyncError.addPlayerNo(builder, playerNo);
    return RmmResSyncError.endRmmResSyncError(builder);
  }

  public static void startRmmResSyncError(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPlayerNo(FlatBufferBuilder builder, byte playerNo) { builder.addByte(0, playerNo, 0); }
  public static void addReason(FlatBufferBuilder builder, byte reason) { builder.addByte(1, reason, 0); }
  public static int endRmmResSyncError(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

