// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmmRoomState {
  private RmmRoomState() { }
  public static final byte Open = 0;
  public static final byte Play = 1;
  public static final byte Closed = 2;

  public static final String[] names = { "Open", "Play", "Closed", };

  public static String name(int e) { return names[e]; }
}

