// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmSkillType {
  private RmSkillType() { }
  public static final short None = 0;
  public static final short IceSmash = 1;
  public static final short IceWhirlWind = 2;
  public static final short MultiArrow = 3;
  public static final short HolyArrow = 4;
  public static final short Lightning = 5;
  public static final short MultiBolt = 6;

  public static final String[] names = { "None", "IceSmash", "IceWhirlWind", "MultiArrow", "HolyArrow", "Lightning", "MultiBolt", };

  public static String name(int e) { return names[e]; }
}

