// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public class RmsMetaSet extends Table {
  public static RmsMetaSet getRootAsRmsMetaSet(ByteBuffer _bb) { return getRootAsRmsMetaSet(_bb, new RmsMetaSet()); }
  public static RmsMetaSet getRootAsRmsMetaSet(ByteBuffer _bb, RmsMetaSet obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RmsMetaSet __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public RmsExp4LevelUp exp4LevelUp(int j) { return exp4LevelUp(new RmsExp4LevelUp(), j); }
  public RmsExp4LevelUp exp4LevelUp(RmsExp4LevelUp obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__vector(o) + j * 8, bb) : null; }
  public int exp4LevelUpLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public RmsUnitStatic unitStatic(int j) { return unitStatic(new RmsUnitStatic(), j); }
  public RmsUnitStatic unitStatic(RmsUnitStatic obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__vector(o) + j * 40, bb) : null; }
  public int unitStaticLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public RmsUnitBalance unitBalance(int j) { return unitBalance(new RmsUnitBalance(), j); }
  public RmsUnitBalance unitBalance(RmsUnitBalance obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__vector(o) + j * 28, bb) : null; }
  public int unitBalanceLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public RmsAbnormalBalance abnormalBalance(int j) { return abnormalBalance(new RmsAbnormalBalance(), j); }
  public RmsAbnormalBalance abnormalBalance(RmsAbnormalBalance obj, int j) { int o = __offset(10); return o != 0 ? obj.__init(__vector(o) + j * 16, bb) : null; }
  public int abnormalBalanceLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public RmsSkillBalance skillBalance(int j) { return skillBalance(new RmsSkillBalance(), j); }
  public RmsSkillBalance skillBalance(RmsSkillBalance obj, int j) { int o = __offset(12); return o != 0 ? obj.__init(__vector(o) + j * 24, bb) : null; }
  public int skillBalanceLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public RmsHeroExpGet heroExpGet(int j) { return heroExpGet(new RmsHeroExpGet(), j); }
  public RmsHeroExpGet heroExpGet(RmsHeroExpGet obj, int j) { int o = __offset(14); return o != 0 ? obj.__init(__vector(o) + j * 8, bb) : null; }
  public int heroExpGetLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public RmsHeroExpUp heroExpUp(int j) { return heroExpUp(new RmsHeroExpUp(), j); }
  public RmsHeroExpUp heroExpUp(RmsHeroExpUp obj, int j) { int o = __offset(16); return o != 0 ? obj.__init(__vector(o) + j * 8, bb) : null; }
  public int heroExpUpLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public RmsHeroRevival heroRevival(int j) { return heroRevival(new RmsHeroRevival(), j); }
  public RmsHeroRevival heroRevival(RmsHeroRevival obj, int j) { int o = __offset(18); return o != 0 ? obj.__init(__vector(o) + j * 8, bb) : null; }
  public int heroRevivalLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public RmsLeagueBalance leagueBalance(int j) { return leagueBalance(new RmsLeagueBalance(), j); }
  public RmsLeagueBalance leagueBalance(RmsLeagueBalance obj, int j) { int o = __offset(20); return o != 0 ? obj.__init(__vector(o) + j * 12, bb) : null; }
  public int leagueBalanceLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public RmsAnimationInfo animationInfo(int j) { return animationInfo(new RmsAnimationInfo(), j); }
  public RmsAnimationInfo animationInfo(RmsAnimationInfo obj, int j) { int o = __offset(22); return o != 0 ? obj.__init(__vector(o) + j * 52, bb) : null; }
  public int animationInfoLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public RmsVariable variable() { return variable(new RmsVariable()); }
  public RmsVariable variable(RmsVariable obj) { int o = __offset(24); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createRmsMetaSet(FlatBufferBuilder builder,
      int exp4LevelUpOffset,
      int unitStaticOffset,
      int unitBalanceOffset,
      int abnormalBalanceOffset,
      int skillBalanceOffset,
      int heroExpGetOffset,
      int heroExpUpOffset,
      int heroRevivalOffset,
      int leagueBalanceOffset,
      int animationInfoOffset,
      int variableOffset) {
    builder.startObject(11);
    RmsMetaSet.addVariable(builder, variableOffset);
    RmsMetaSet.addAnimationInfo(builder, animationInfoOffset);
    RmsMetaSet.addLeagueBalance(builder, leagueBalanceOffset);
    RmsMetaSet.addHeroRevival(builder, heroRevivalOffset);
    RmsMetaSet.addHeroExpUp(builder, heroExpUpOffset);
    RmsMetaSet.addHeroExpGet(builder, heroExpGetOffset);
    RmsMetaSet.addSkillBalance(builder, skillBalanceOffset);
    RmsMetaSet.addAbnormalBalance(builder, abnormalBalanceOffset);
    RmsMetaSet.addUnitBalance(builder, unitBalanceOffset);
    RmsMetaSet.addUnitStatic(builder, unitStaticOffset);
    RmsMetaSet.addExp4LevelUp(builder, exp4LevelUpOffset);
    return RmsMetaSet.endRmsMetaSet(builder);
  }

  public static void startRmsMetaSet(FlatBufferBuilder builder) { builder.startObject(11); }
  public static void addExp4LevelUp(FlatBufferBuilder builder, int exp4LevelUpOffset) { builder.addOffset(0, exp4LevelUpOffset, 0); }
  public static void startExp4LevelUpVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static void addUnitStatic(FlatBufferBuilder builder, int unitStaticOffset) { builder.addOffset(1, unitStaticOffset, 0); }
  public static void startUnitStaticVector(FlatBufferBuilder builder, int numElems) { builder.startVector(40, numElems, 4); }
  public static void addUnitBalance(FlatBufferBuilder builder, int unitBalanceOffset) { builder.addOffset(2, unitBalanceOffset, 0); }
  public static void startUnitBalanceVector(FlatBufferBuilder builder, int numElems) { builder.startVector(28, numElems, 4); }
  public static void addAbnormalBalance(FlatBufferBuilder builder, int abnormalBalanceOffset) { builder.addOffset(3, abnormalBalanceOffset, 0); }
  public static void startAbnormalBalanceVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 4); }
  public static void addSkillBalance(FlatBufferBuilder builder, int skillBalanceOffset) { builder.addOffset(4, skillBalanceOffset, 0); }
  public static void startSkillBalanceVector(FlatBufferBuilder builder, int numElems) { builder.startVector(24, numElems, 4); }
  public static void addHeroExpGet(FlatBufferBuilder builder, int heroExpGetOffset) { builder.addOffset(5, heroExpGetOffset, 0); }
  public static void startHeroExpGetVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static void addHeroExpUp(FlatBufferBuilder builder, int heroExpUpOffset) { builder.addOffset(6, heroExpUpOffset, 0); }
  public static void startHeroExpUpVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static void addHeroRevival(FlatBufferBuilder builder, int heroRevivalOffset) { builder.addOffset(7, heroRevivalOffset, 0); }
  public static void startHeroRevivalVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static void addLeagueBalance(FlatBufferBuilder builder, int leagueBalanceOffset) { builder.addOffset(8, leagueBalanceOffset, 0); }
  public static void startLeagueBalanceVector(FlatBufferBuilder builder, int numElems) { builder.startVector(12, numElems, 4); }
  public static void addAnimationInfo(FlatBufferBuilder builder, int animationInfoOffset) { builder.addOffset(9, animationInfoOffset, 0); }
  public static void startAnimationInfoVector(FlatBufferBuilder builder, int numElems) { builder.startVector(52, numElems, 4); }
  public static void addVariable(FlatBufferBuilder builder, int variableOffset) { builder.addOffset(10, variableOffset, 0); }
  public static int endRmsMetaSet(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

