// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmStatType {
  private RmStatType() { }
  public static final byte None = 0;
  public static final byte Health = 1;
  public static final byte PhysicalAttack = 2;
  public static final byte MagicalAttack = 3;
  public static final byte PhysicalDefence = 4;
  public static final byte MagicalDefence = 5;
  public static final byte HealthBoost = 31;
  public static final byte PhysicalAttackBoost = 32;
  public static final byte MagicalAttackBoost = 33;
  public static final byte PhysicalDefenceBoost = 34;
  public static final byte MagicalDefenceBoost = 35;
  public static final byte MoveSpeedBoost = 61;
  public static final byte AttackSpeedBoost = 62;
  public static final byte DamageReduce = 63;
  public static final byte CooltimeReduce = 64;

  public static final String[] names = { "None", "Health", "PhysicalAttack", "MagicalAttack", "PhysicalDefence", "MagicalDefence", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "HealthBoost", "PhysicalAttackBoost", "MagicalAttackBoost", "PhysicalDefenceBoost", "MagicalDefenceBoost", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "MoveSpeedBoost", "AttackSpeedBoost", "DamageReduce", "CooltimeReduce", };

  public static String name(int e) { return names[e]; }
}

