// automatically generated by the FlatBuffers compiler, do not modify

package com.clue.fbs;

public class RmUnitName {
  private RmUnitName() { }
  public static final short None = 0;
  public static final short IceKnight = 1;
  public static final short HolyArcher = 2;
  public static final short Wizard = 3;
  public static final short Valkyrie = 4;
  public static final short Cannon = 5;
  public static final short DeathCaller = 6;
  public static final short Dullahan = 7;
  public static final short Eros = 8;
  public static final short Gangster = 9;
  public static final short General = 10;
  public static final short Gunner = 11;
  public static final short IceQueen = 12;
  public static final short Immortal = 13;
  public static final short LineMan = 14;
  public static final short Monk = 15;
  public static final short Paoh = 16;
  public static final short Pharaoh = 17;
  public static final short Priest = 18;
  public static final short SandWitch = 19;
  public static final short Succubus = 20;
  public static final short Thief = 21;
  public static final short Anna = 22;
  public static final short SkeletonBasic = 101;
  public static final short SkeletonBow = 102;
  public static final short SkeletonKing = 103;
  public static final short SkeletonMage = 104;
  public static final short Tower = 201;
}

